export const COIN_LIST_FETCHED = 'COIN_LIST_FETCHED';
export const COIN_PROFILE_FETCHED = 'COIN_PROFILE_FETCHED';
export const COIN_SOCIAL_FETCHED = 'COIN_SOCIAL_FETCHED';
export const COIN_AGGREGATE_FETCHED = 'COIN_AGGREGATE_FETCHED';
export const COIN_HISTORY_FETCHED = 'COIN_HISTORY_FETCHED';
export const COIN_PRICE_FETCHED = 'COIN_PRICE_FETCHED';
export const FETCHING = 'FETCHING';
export const ERRORED = 'ERRORED';
